(() => {
  const getDb=()=>window.FINANCPLANTOES_DB||window.db||null;
  const getUser=()=>window.FINANCPLANTOES_USER||window.user||null;
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const labels={residence:'Residência',clinic:'Clínica',trip:'Viagem',event:'Evento',team:'Equipe',project:'Projeto',other:'Outro'};
  const id=()=>crypto.randomUUID();
  function renderSpaceActions(s){return `<span class="toolbar"><button class="link-button" type="button" onclick="editSpace('${s.id}')">Editar</button><button class="link-button danger-text" type="button" onclick="deleteSpace('${s.id}')">Excluir</button></span>`;}
  function openSpaceForm(space){
    const root=document.getElementById('modalRoot');
    root.innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="modal-head"><div><p class="eyebrow">ESPAÇO</p><h3>${space?'Editar espaço':'Novo espaço'}</h3></div><button class="close-btn" type="button" onclick="closeModal()">×</button></div><form id="spaceForm"><div class="modal-grid"><label>Nome do espaço<input name="name" maxlength="100" required value="${esc(space?.name||'')}"></label><label>Tipo<select name="space_type" required>${Object.entries(labels).map(([v,t])=>`<option value="${v}" ${space?.space_type===v?'selected':''}>${t}</option>`).join('')}</select></label><label class="wide">Descrição<textarea name="description" maxlength="500">${esc(space?.description||'')}</textarea></label><label>Início<input name="start_date" type="date" value="${space?.start_date||''}"></label><label>Fim<input name="end_date" type="date" value="${space?.end_date||''}"></label></div><div class="modal-actions"><button class="secondary" type="button" onclick="closeModal()">Cancelar</button><button class="primary" type="submit">${space?'Salvar alterações':'Criar espaço'}</button></div></form></div></div>`;
    document.getElementById('spaceForm').onsubmit=async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;try{const db=getDb(),u=getUser();if(!db||!u)throw new Error('Sessão não conectada.');const f=new FormData(e.currentTarget);const row={name:String(f.get('name')).trim(),space_type:f.get('space_type'),description:String(f.get('description')||'').trim()||null,start_date:f.get('start_date')||null,end_date:f.get('end_date')||null};if(!row.name)throw new Error('Informe o nome do espaço.');if(row.start_date&&row.end_date&&row.end_date<row.start_date)throw new Error('A data final não pode ser anterior à inicial.');if(space){const r=await db.from('spaces').update(row).eq('id',space.id).eq('owner_id',u.id);if(r.error)throw r.error;}else{const sid=id();const r=await db.from('spaces').insert({id:sid,owner_id:u.id,...row,archived:false});if(r.error)throw r.error;const m=await db.from('space_members').upsert({space_id:sid,user_id:u.id,role:'owner',status:'active'},{onConflict:'space_id,user_id'});if(m.error)throw m.error;}closeModal();if(typeof window.loadAll==='function')await window.loadAll();else location.reload();}catch(err){alert(err?.message||'Não foi possível salvar o espaço.');btn.disabled=false;}};
  }
  window.editSpace=async sid=>{const db=getDb();if(!db)return alert('Supabase não conectado.');const r=await db.from('spaces').select('id,name,space_type,description,start_date,end_date,archived,owner_id').eq('id',sid).maybeSingle();if(r.error)return alert(r.error.message);if(!r.data)return alert('Espaço não encontrado.');openSpaceForm(r.data);};
  window.deleteSpace=async sid=>{const db=getDb(),u=getUser();if(!db||!u)return alert('Sessão não conectada.');const r=await db.from('spaces').select('id,name,owner_id,archived').eq('id',sid).maybeSingle();if(r.error)return alert(r.error.message);if(!r.data)return alert('Espaço não encontrado.');if(r.data.owner_id!==u.id)return alert('Somente o proprietário pode excluir este espaço.');if(!confirm(`Excluir o espaço “${r.data.name}”? Esta ação não deve ser usada se houver histórico financeiro importante.`))return;const del=await db.from('spaces').delete().eq('id',sid).eq('owner_id',u.id);if(del.error){const arch=await db.from('spaces').update({archived:true}).eq('id',sid).eq('owner_id',u.id);if(arch.error)return alert(`Não foi possível excluir ou inativar: ${arch.error.message}`);alert('O espaço possui dados vinculados e não pode ser apagado. Ele foi inativado para preservar o histórico.');}if(typeof window.loadAll==='function')await window.loadAll();else location.reload();};
  window.openSpace=async sid=>{const db=getDb(),u=getUser();if(!db||!u)return alert('Sessão não conectada.');const r=await db.from('spaces').select('id,name,space_type,description,start_date,end_date,archived,owner_id').eq('id',sid).maybeSingle();if(r.error)return alert(r.error.message);if(!r.data)return alert('Espaço não encontrado.');const s=r.data;const root=document.getElementById('modalRoot');root.innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="modal-head"><div><p class="eyebrow">ESPAÇO</p><h3>${esc(s.name)}</h3><p class="muted">${esc(labels[s.space_type]||s.space_type)}${s.archived?' · Inativo':''}</p></div><button class="close-btn" type="button" onclick="closeModal()">×</button></div><div class="detail-card"><p>${esc(s.description||'Sem descrição.')}</p><small>${s.start_date||'—'} → ${s.end_date||'—'}</small></div><div class="modal-actions"><button class="secondary" type="button" onclick="editSpace('${s.id}')">Editar</button><button class="link-button danger-text" type="button" onclick="deleteSpace('${s.id}')">Excluir</button><button class="primary" type="button" onclick="closeModal()">Fechar</button></div></div></div>`;};
  function wire(){const add=document.getElementById('addSpace');if(add){add.onclick=()=>openSpaceForm(null);} }
  document.addEventListener('DOMContentLoaded',wire);window.openSpaceForm=openSpaceForm;
})();