(() => {
  const db = () => window.FINANCPLANTOES_DB || null;
  const user = async () => { const c=db(); if(!c) throw new Error('Supabase não conectado.'); const r=await c.auth.getSession(); if(r.error) throw r.error; if(!r.data.session?.user) throw new Error('Sessão não encontrada.'); return r.data.session.user; };
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const types={residence:'Residência',clinic:'Clínica',trip:'Viagem',event:'Evento',team:'Equipe',project:'Projeto',other:'Outro'};
  function form(space){
    const root=document.getElementById('modalRoot');
    root.innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="modal-head"><div><p class="eyebrow">ESPAÇO</p><h3>${space?'Editar espaço':'Novo espaço'}</h3></div><button class="close-btn" type="button" onclick="closeModal()">×</button></div><form id="spaceForm"><div class="modal-grid"><label>Nome<input name="name" required maxlength="100" value="${esc(space?.name||'')}"></label><label>Tipo<select name="space_type" required>${Object.entries(types).map(([v,t])=>`<option value="${v}" ${space?.space_type===v?'selected':''}>${t}</option>`).join('')}</select></label><label class="wide">Descrição<textarea name="description" maxlength="500">${esc(space?.description||'')}</textarea></label><label>Início<input name="start_date" type="date" value="${space?.start_date||''}"></label><label>Fim<input name="end_date" type="date" value="${space?.end_date||''}"></label></div><div class="modal-actions"><button class="secondary" type="button" onclick="closeModal()">Cancelar</button><button class="primary" type="submit">${space?'Salvar':'Criar espaço'}</button></div></form></div></div>`;
    document.getElementById('spaceForm').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const c=db(),u=await user(),f=new FormData(e.currentTarget),row={name:String(f.get('name')).trim(),space_type:f.get('space_type'),description:String(f.get('description')||'').trim()||null,start_date:f.get('start_date')||null,end_date:f.get('end_date')||null};if(!row.name)throw new Error('Informe o nome do espaço.');if(space){const r=await c.from('spaces').update(row).eq('id',space.id).eq('owner_id',u.id);if(r.error)throw r.error;}else{const sid=crypto.randomUUID();const r=await c.from('spaces').insert({id:sid,owner_id:u.id,...row,archived:false});if(r.error)throw r.error;const m=await c.from('space_members').insert({space_id:sid,user_id:u.id,role:'owner',status:'active'});if(m.error)throw m.error;}closeModal();await window.loadAll?.();}catch(x){alert(x.message||'Não foi possível salvar o espaço.');b.disabled=false;}};
  }
  window.editSpace=async sid=>{try{const c=db();await user();const r=await c.from('spaces').select('id,name,space_type,description,start_date,end_date,archived,owner_id').eq('id',sid).maybeSingle();if(r.error)throw r.error;if(!r.data)throw new Error('Espaço não encontrado.');form(r.data);}catch(x){alert(x.message);}};
  window.deleteSpace=async sid=>{try{const c=db(),u=await user();const r=await c.from('spaces').select('id,name,owner_id').eq('id',sid).maybeSingle();if(r.error)throw r.error;if(!r.data)throw new Error('Espaço não encontrado.');if(r.data.owner_id!==u.id)throw new Error('Somente o proprietário pode excluir este espaço.');if(!confirm(`Excluir “${r.data.name}”?`))return;let d=await c.from('spaces').delete().eq('id',sid).eq('owner_id',u.id);if(d.error){d=await c.from('spaces').update({archived:true}).eq('id',sid).eq('owner_id',u.id);if(d.error)throw d.error;alert('O espaço possui dados vinculados e foi inativado para preservar o histórico.');}await window.loadAll?.();}catch(x){alert(x.message||'Não foi possível excluir o espaço.');}};
  window.openSpace=async sid=>{try{const c=db();const u=await user();const r=await c.from('spaces').select('*').eq('id',sid).maybeSingle();if(r.error)throw r.error;if(!r.data)throw new Error('Espaço não encontrado.');const s=r.data,root=document.getElementById('modalRoot');const owner=s.owner_id===u.id;root.innerHTML=`<div class="modal-backdrop"><div class="modal"><div class="modal-head"><div><p class="eyebrow">ESPAÇO</p><h3>${esc(s.name)}</h3><p class="muted">${esc(types[s.space_type]||s.space_type)}</p></div><button class="close-btn" onclick="closeModal()">×</button></div><div class="detail-card"><p>${esc(s.description||'Sem descrição.')}</p></div><div class="modal-actions"><button class="secondary" onclick="editSpace('${s.id}')">Editar</button><button class="secondary" onclick="openSpaceMembers('${s.id}')">Membros e convites</button>${owner?`<button class="link-button danger-text" onclick="deleteSpace('${s.id}')">Excluir</button>`:''}<button class="primary" onclick="closeModal()">Fechar</button></div></div></div>`;}catch(x){alert(x.message);}};
  function wire(){document.getElementById('addSpace')?.addEventListener('click',()=>form(null));}
  document.addEventListener('DOMContentLoaded',wire);
})();