(() => {
  const page=document.body.dataset.workspacePage;
  const cfg=window.FINANCPLANTOES_SUPABASE;
  const db=()=>window.FINANCPLANTOES_DB||(window.supabase?.createClient&&cfg?window.supabase.createClient(cfg.url,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:true}}):null);
  const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v||0));
  async function start(){
    const c=db(); if(!c) return showError('Supabase não conectado.');
    const {data,error}=await c.auth.getSession(); if(error) return showError(error.message);
    if(!data.session?.user){location.href='index.html';return;}
    const u=data.session.user;
    document.getElementById('pageUser').textContent=u.user_metadata?.full_name||u.email||'Minha conta';
    document.getElementById('logoutPage').onclick=async()=>{await c.auth.signOut();location.href='index.html';};
    document.getElementById('backHome').onclick=()=>location.href='index.html';
    if(page==='finance') return finance(c,u);
    if(page==='expenses') return expenses(c,u);
    if(page==='spaces') return spaces(c,u);
  }
  async function finance(c,u){
    title('Financeiro','Recebimentos e baixas financeiras.');
    const r=await c.from('receivables').select('*').eq('user_id',u.id).neq('status','cancelled').order('expected_date'); if(r.error)return showError(r.error.message);
    const rows=r.data||[],pending=rows.filter(x=>x.status!=='received').reduce((a,x)=>a+Number(x.amount||0),0),received=rows.filter(x=>x.status==='received').reduce((a,x)=>a+Number(x.amount||0),0);
    document.getElementById('pageContent').innerHTML=`<div class="page-cards"><div><small>Pendente</small><strong>${money(pending)}</strong></div><div><small>Recebido</small><strong>${money(received)}</strong></div></div><div class="page-list">${rows.map(x=>`<article class="page-row"><div><strong>${esc(x.description)}</strong><small>${esc(x.expected_date||'')} · ${x.status==='received'?'Recebido':'Pendente'}</small></div><div class="page-row-actions"><b>${money(x.amount)}</b><button class="${x.status==='received'?'secondary':'primary'} page-action" data-id="${x.id}">${x.status==='received'?'Editar recebimento':'Marcar recebido'}</button></div></article>`).join('')||'<p class="muted">Nenhum recebível.</p>'}</div>`;
    document.querySelectorAll('.page-action').forEach(b=>b.onclick=()=>receive(c,u,b.dataset.id));
  }
  async function receive(c,u,id){const r=await c.from('receivables').select('*').eq('id',id).eq('user_id',u.id).maybeSingle();if(r.error||!r.data)return;const x=r.data;document.getElementById('pageContent').innerHTML=`<div class="page-form"><h3>${esc(x.description)}</h3><p class="muted">${money(x.amount)}</p><label>Data<input id="rd" type="date" value="${x.received_date||new Date().toISOString().slice(0,10)}"></label><label>Forma de pagamento<select id="rm"><option value="pix">PIX</option><option value="transfer">Transferência</option><option value="cash">Dinheiro</option><option value="card">Cartão</option><option value="other">Outro</option></select></label><label>Observação<textarea id="rn">${esc(x.notes||'')}</textarea></label><div class="page-actions"><button class="secondary" id="rb">Cancelar</button><button class="primary" id="rs">Confirmar recebimento</button></div></div>`;document.getElementById('rb').onclick=()=>finance(c,u);document.getElementById('rs').onclick=async e=>{e.currentTarget.disabled=true;const q=await c.from('receivables').update({status:'received',received_date:document.getElementById('rd').value,payment_method:document.getElementById('rm').value,notes:document.getElementById('rn').value||null}).eq('id',id).eq('user_id',u.id);if(q.error){alert(q.error.message);e.currentTarget.disabled=false;return;}finance(c,u);};}
  async function expenses(c,u){title('Despesas compartilhadas','Despesas por espaço, com participantes cadastrados.');const [s,m,p,e]=await Promise.all([c.from('spaces').select('id,name').order('name'),c.from('space_members').select('space_id,user_id,role,status').eq('status','active'),c.from('profiles').select('user_id,display_name').order('display_name'),c.from('expenses').select('*').order('expense_date',{ascending:false}).limit(100)]);if(s.error||m.error||e.error)return showError((s.error||m.error||e.error).message);const active=m.data||[],spaces=(s.data||[]).filter(x=>active.some(z=>z.space_id===x.id&&z.user_id===u.id));const names=Object.fromEntries((p.data||[]).map(x=>[x.user_id,x.display_name||'Usuário']));names[u.id]=names[u.id]||u.user_metadata?.full_name||u.email?.split('@')[0];document.getElementById('pageContent').innerHTML=`<div class="page-toolbar"><button class="primary" id="newExpense">+ Nova despesa compartilhada</button></div><div class="page-list">${(e.data||[]).filter(x=>spaces.some(s=>s.id===x.space_id)).map(x=>`<article class="page-row"><div><strong>${esc(x.description)}</strong><small>${money(x.amount)} · ${esc(spaces.find(s=>s.id===x.space_id)?.name||'Espaço')} · Pago por ${esc(names[x.paid_by]||'Usuário')}</small></div></article>`).join('')||'<p class="muted">Nenhuma despesa compartilhada.</p>'}</div>`;document.getElementById('newExpense').onclick=()=>newExpense(c,u,spaces,active,names);}
  function newExpense(c,u,spaces,members,names){document.getElementById('pageContent').innerHTML=`<div class="page-form"><h3>Nova despesa compartilhada</h3><label>Espaço<select id="es">${spaces.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}</select></label><label>Descrição<input id="ed" placeholder="Ex.: Mercado"></label><label>Valor<input id="ea" type="number" min="0.01" step="0.01"></label><label>Data<input id="et" type="date" value="${new Date().toISOString().slice(0,10)}"></label><label>Quem pagou<select id="ep"></select></label><fieldset><legend>Dividir entre</legend><div id="eb"></div></fieldset><div class="page-actions"><button class="secondary" id="ec">Cancelar</button><button class="primary" id="ev">Salvar despesa</button></div></div>`;const refresh=()=>{const sid=document.getElementById('es').value,ids=[...new Set(members.filter(m=>m.space_id===sid).map(m=>m.user_id))],p=document.getElementById('ep'),b=document.getElementById('eb');p.innerHTML=ids.map(id=>`<option value="${id}">${esc(names[id]||'Usuário')}</option>`).join('');if(ids.includes(u.id))p.value=u.id;b.innerHTML=ids.map(id=>`<label class="participant"><input type="checkbox" value="${id}" checked> ${esc(names[id]||'Usuário')}</label>`).join('')||'<p class="danger-text">Nenhum membro ativo neste espaço.</p>';};document.getElementById('es').onchange=refresh;document.getElementById('ec').onclick=()=>expenses(c,u);refresh();document.getElementById('ev').onclick=async e=>{e.currentTarget.disabled=true;const sid=document.getElementById('es').value,ids=[...document.querySelectorAll('#eb input:checked')].map(x=>x.value),amount=Number(document.getElementById('ea').value),desc=document.getElementById('ed').value.trim(),payer=document.getElementById('ep').value;if(!sid||!ids.length||!amount||!desc||!payer){alert('Preencha todos os campos e selecione participantes.');e.currentTarget.disabled=false;return;}const id=crypto.randomUUID(),q=await c.from('expenses').insert({id,space_id:sid,created_by:u.id,paid_by:payer,description:desc,amount,expense_date:document.getElementById('et').value,split_method:'equal'});if(q.error){alert(q.error.message);e.currentTarget.disabled=false;return;}const share=Math.round(amount/ids.length*100)/100,rows=ids.map(uid=>({id:crypto.randomUUID(),expense_id:id,user_id:uid,amount:share,percentage:100/ids.length,settled_amount:uid===payer?share:0,payment_status:uid===payer?'confirmed':'unpaid'})),z=await c.from('expense_splits').insert(rows);if(z.error){await c.from('expenses').delete().eq('id',id);alert(z.error.message);e.currentTarget.disabled=false;return;}expenses(c,u);};}
  async function spaces(c,u){title('Espaços','Locais, grupos e eventos compartilhados.');const r=await c.from('spaces').select('*').or(`owner_id.eq.${u.id},id.in.(${await memberSpaceIds(c,u.id)})`).order('name');if(r.error)return showError(r.error.message);document.getElementById('pageContent').innerHTML=`<div class="page-toolbar"><button class="primary" id="newSpace">+ Novo espaço</button></div><div class="page-list">${(r.data||[]).map(s=>`<article class="page-row"><div><strong>${esc(s.name)}</strong><small>${esc(s.space_type||'')} · ${s.archived?'Inativo':'Ativo'}</small></div><div class="page-row-actions"><button class="secondary" data-edit="${s.id}">Editar</button><button class="secondary" data-members="${s.id}">Membros</button>${s.owner_id===u.id?`<button class="link-button danger-text" data-delete="${s.id}">Excluir</button>`:''}</div></article>`).join('')||'<p class="muted">Nenhum espaço.</p>'}</div>`;document.getElementById('newSpace').onclick=()=>window.openSpaceFormStandalone?.();document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>window.editSpace(b.dataset.edit));document.querySelectorAll('[data-members]').forEach(b=>b.onclick=()=>window.openSpaceMembers(b.dataset.members));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>window.deleteSpace(b.dataset.delete));}
  async function memberSpaceIds(c,uid){const r=await c.from('space_members').select('space_id').eq('user_id',uid).eq('status','active');return (r.data||[]).map(x=>x.space_id).join(',')||'00000000-0000-0000-0000-000000000000';}
  function title(t,s){document.getElementById('pageTitle').textContent=t;document.getElementById('pageSubtitle').textContent=s;}
  function showError(m){document.getElementById('pageContent').innerHTML=`<p class="danger-text">${esc(m)}</p>`;}
  document.addEventListener('DOMContentLoaded',start);
})();